### ISSUE TITLE
Speed up build by removing unnecessary compile steps

### ISSUE THREAD

**Issue by anidev** [VTAstrobotics/Robot-2017#12]
Includes the following changes:
- [ ] Remove message generation for unnecessary languages (Lisp, Python, etc)
- [x] Remove entire rosserial submodule, instead depend on system-wide rosserial-python package

Add other potential tasks here as necessary

**Comment by matthew-conner** [comment]
Once we have successfully test the watchdog I will experiment with removing the rosserial submodule - I would like to make sure the serial communication actually works first before we start adding new variables.

**Comment by anidev** [comment]
Sounds good, I'm working on disabling the extra messages

**Comment by matthew-conner** [comment]
Update: still waiting on a working watchdog with rosserial - possible we may go with a custom protocol if we continue to have issues - in that case any rosserial slowdowns would be gone.
