### ISSUE TITLE
Set up Robot->NUC feedback for autonomy

### ISSUE THREAD

**Issue by anidev** [VTAstrobotics/Robot-2017#4]
Will require a) new message and b) data from the motor controller library

**Comment by matthew-conner** [comment]
New message type has been created, a publisher node has been created, and the publisher has been integrated into the robot_exec code. However, we still are waiting on the getRPM( ) methods from controls, so for the moment I have implemented dummy logging statements and am sending random values.

**Comment by anidev** [comment]
Mostly done but need to implement getters now that it is supported in library

**Comment by matthew-conner** [comment]
Re. last comment - does anything still need to be done for this?

**Comment by anidev** [comment]
State machine code in #15, in addition getters still need to be used in `RobotExec::publishMotors`

**Comment by matthew-conner** [comment]
Is it just the setters that have been implemented then? I thought most of the motor library had already been implemented.

**Comment by matthew-conner** [comment]
Will add in the getter methods tonight, probably within your motor receive branch, since that is the only active branch right now that is doing stuff with the vesc library

**Comment by matthew-conner** [comment]
Added - can't really test it unless the motors are actually wired up though. Also, we can't publish lift position yet because apparently that is going to be implemented as a seperate system.

**Comment by anidev** [comment]
Fixed in #15 which takes care of all the motor receiving and feedback
