### ISSUE TITLE
Create Watchdog receiving message+node

### ISSUE THREAD

**Issue by anidev** [VTAstrobotics/Robot-2017#5]
Node will receive from Watchdog via rosserial and forward to logging, possibly autonomy as well

**Comment by anidev** [comment]
Pending testing

**Comment by matthew-conner** [comment]
Issue on the controls side - they can't see the data being transmitted (trying to view it over TeraTerm). Hopefully we will be able to get it working at the meeting tonight.

**Comment by anidev** [comment]
issue has been taken care of, serial node has been merged into launch files, additional watchdog node is unnecessary
